# mkdocs.yml
theme:
  logo: https://audunsh.github.io/slides/assets/owl_logo.png
  name: "material"
  favicon: https://raw.githubusercontent.com/audunsh/btjenesten/master/graphics/favicon.png
  palette:
    primary: teal

site_name : Open World

plugins:
  - search
  - mkdocstrings

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - Test: Untitled12.md
  - Test 2: Untitled13.md
  - Developers: developers.md
