# mkdocs.yml
theme:
  logo: https://audunsh.github.io/slides/assets/owl_logo.png
  name: "material"
  favicon: https://raw.githubusercontent.com/audunsh/openworld/master/docs/assets/owl_favicon.png
  palette:
    primary: root

site_name : Open World

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - mkdocstrings

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - Simulation tools:
    - Molecular dynamics: mdsim.md
    - Lattice dynamics: ltsim.md
    - Quantum mechanics: qmsim.md
    - Quantum chemistry: qcsim.md
  - Pathways:
    - Thermodynamics: thermpaths.md
    - Experiments: expaths.md
    - Quantum mechanics: qmpaths.md
  - Test: Untitled12.md
  - Developers: developers.md
