# mkdocs.yml
theme:
  logo: https://audunsh.github.io/slides/assets/owl_logo.png
  name: "material"
  favicon: https://raw.githubusercontent.com/audunsh/openworld/master/docs/assets/owl_favicon.png
  palette:
    primary: root

site_name : Open World

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - mkdocstrings
  - mkdocs-jupyter
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - Simulation tools:
    - Molecular dynamics: mdsim.md
    - Lattice dynamics: ltsim.md
    - Quantum mechanics: qmsim.md
    - Quantum chemistry: qcsim.md
    - Gaussian Process Regression:
      - Polynomial Regression: polynomial_regression.ipynb
      - Covariance: Covariance.ipynb
      - Kernels: Kernels.ipynb
      - Introduction to Gaussian Process Regression: GPR_intro.ipynb
      - Quick tutorial on GPR module: quick_gpr_tutorial.ipynb
  - Pathways:
    - Thermodynamics:
      - Temperature: bubblebox_learning.ipynb
    - Experiments: expaths.md
    - Quantum mechanics: qmpaths.md
  - Internal guides:
    - Getting started:
      - Getting started: getting_started.md
      - Github: github.md
      - github.uio.no: github_uio.md
      - PyPI (pip): pip.md
      - MKDocs: mkdocs.md
      - Markdown: markdown.md
    - Food for thought:
      - Writing for students: writing.md
      - Literature: literature.md
      - Conventions: conventions.md
  - Developers: developers.md
