# mkdocs.yml
theme:
  logo: https://audunsh.github.io/slides/assets/owl_logo.png
  name: "material"
  favicon: https://raw.githubusercontent.com/audunsh/openworld/master/docs/assets/owl_favicon.png
  palette:
    primary: root

site_name : Open World

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - mkdocstrings
  - mkdocs-jupyter
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - Simulation tools:
    - Molecular dynamics: mdsim.md
    - Lattice dynamics: ltsim.md
    - Quantum mechanics: qmsim.md
    - Quantum chemistry: qcsim.md
    - Gaussian Process Regression:
      - Polynomial Regression: "Simulation tools/Gaussian process regression/polynomial_regression.ipynb"
      - Covariance: "Simulation tools/Gaussian process regression/Covariance.ipynb"
      - Kernels: "Simulation tools/Gaussian process regression/Kernels.ipynb"
      - Introduction to Gaussian Process Regression: "Simulation tools/Gaussian process regression/GPR_intro.ipynb"
      - Quick tutorial on GPR module: "Simulation tools/Gaussian process regression/quick_gpr_tutorial.ipynb"
  - Pathways:
    - Thermodynamics:
      - Temperature: "Pathways/Thermodynamics/bubblebox_learning.ipynb"
    - Experiments: expaths.md
    - Quantum mechanics:
      - Introduction to quantum thinking: "Pathways/Quantum mechanics/Quantum_thinking.ipynb"
      - Eigenfunctions and eigenstates: "Pathways/Quantum mechanics/eigenfunctions_eigenstates.ipynb"
      - Classical Hydrogen: "Pathways/Quantum mechanics/Classical hydrogen.ipynb"
  - Internal guides:
    - Getting started:
      - Getting started: "Internal guides/Getting started/getting_started.md"
      - Github: "Internal guides/Getting started/github.md"
      - github.uio.no: "Internal guides/Getting started/github_uio.md"
      - PyPI (pip): "Internal guides/Getting started/pip.md"
      - MKDocs: "Internal guides/Getting started/mkdocs.md"
      - Markdown: "Internal guides/Getting started/markdown.md"
    - Food for thought:
      - Writing for students: "Internal guides/Food for thought/writing.md"
      - Literature: "Internal guides/Food for thought/literature.md"
      - Conventions: "Internal guides/Food for thought/conventions.md"
  - Developers: developers.md
